### ISSUE TITLE
Hoping add generating square shape avatar feature

### ISSUE THREAD

**Issue by livrth** [multiavatar/Multiavatar#6]
Hi @giekaton your project is excellent, but in some websites  and Apps, the avatar is a square shape, so It would be better if the `Multiavatar` can support generating square shape avatar.

It seems changing the avatar's shape and spread the background color to the edge can do it, but this change may
cost a lot, even rebuild the project.

So an easier way is adding an option `discard background` , without the circle background, the avatar can fit not only circle shape but the square shape. 

Thank you very much!

**Comment by giekaton** [comment]
Hi, thanks for the idea. I will think how to make it square. Simply making the background as square instead of the circle would make the lower parts of avatar clothes not reaching the bottom of the square border...

But as you've mentioned, you can easily generate an avatar without the background, and then fit it in any shape you prefer. Such feature already exists.

To do so, simply provide the `true` boolean for the second `sansEnv` parameter:

`var svgCode = multiavatar("Binx Bond", true);`

**Comment by h0l4ct13** [comment]
Thank you.

**Comment by jlnrrg** [comment]
Please consider also exposing this flag in the [api](https://api.multiavatar.com/), or updating the readme if it is already possible :pray:

**Comment by pensacola1989** [comment]
hi, @giekaton  great project, I have learn the your readme,but can't find how to config the skin? (for example ,Asian skin),is there any way to do this ?Can I limit the skin color in a range? thx
